### ISSUE TITLE
How did it perform?

### ISSUE THREAD

**Issue by dlidstrom** [MehranSangrasi/AI-Ludo#2]
It would have been interesting to know how the AI performed. Did it play competitively with yourselves? How did it perform against an opponent that moves randomly?

**Comment by MehranSangrasi** [comment]
Sorry for replying late.
At First I was using only one AI Player and told my friends to play the rest (sadly). At that time the AI playing very random. SO they started avoiding the AI tokens ( not killing them) and then that one became very lets say confident and would move headfast into killings and other rewards without fear of death. 

Later I added the rest of players on different models of the same architecture. And the results were interesting: 
- The first player was still attacky
- The Second one followed by the first one was very defensive (ig due to first's attacks
- The third one was in a race to go as it had no attacks from the third

And well. I didn't get further results due to lack of processing.

**Comment by MehranSangrasi** [comment]
Well I guess we can if we start training all the models at the same time and for a long time. I honeslty didn't train it enough. I ran out of time for the submission.

**Comment by MehranSangrasi** [comment]
Did you need something, I might have some changes I could recommend.
